"""Report Generator Module for ResumeAI.
Generates structured Markdown and downloadable PDF analysis reports containing comprehensive
scoring breakdowns, ATS audits, matched/missing skills, strengths, and recommendations.
"""

from pathlib import Path
from typing import Dict, Any
import time

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

from src.config import REPORTS_DIR


class PDFReport(FPDF):
    """Custom styled PDF for ResumeAI analysis."""

    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(37, 99, 235)  # Royal Blue
        self.cell(self.epw, 8, "ResumeAI - Career Match & Resume Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 116, 139)
        self.cell(self.epw, 5, "AI-Powered Technical Assessment & ATS Compatibility Audit", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(self.epw, 10, f"Generated by ResumeAI | Page {self.page_no()}", align="C")


class ReportGenerator:
    """Generates downloadable analysis reports in Markdown and PDF format."""

    def __init__(self):
        pass

    def generate_markdown_report(self, analysis_result: Dict[str, Any]) -> str:
        """Constructs a clean, comprehensive Markdown report."""
        res = analysis_result
        target_domain = res.get("target_domain", "General")
        fit_score = res.get("overall_fit_score", 0)
        rating_label = res.get("rating_label", "Good")
        ats_score = res.get("ats_data", {}).get("ats_score", 0)
        domain_sim = res.get("domain_match_pct", 0)
        personal = res.get("parsed_data", {}).get("personal_info", {})
        cand_name = personal.get("name", "Candidate")

        matched = res.get("scoring_data", {}).get("skill_alignment", {}).get("matched_skills", [])
        matched_str = ", ".join([s["skill_name"] for s in matched]) if matched else "None detected"

        missing = res.get("scoring_data", {}).get("skill_alignment", {}).get("missing_skills", [])
        missing_str = ", ".join([s["skill_name"] for s in missing[:8]]) if missing else "None"

        strengths = res.get("strengths", [])
        weaknesses = res.get("weaknesses", [])
        recommendations = res.get("improvements", [])

        md = f"""# ResumeAI — Analysis Report

**Candidate Name:** {cand_name}  
**Target Domain:** {target_domain}  
**Date of Assessment:** {time.strftime('%B %d, %Y')}  

---

## 1. Executive Summary & Scores

* **AI Resume Fit Score:** **{fit_score}/100** ({rating_label})
* **Domain Alignment Score:** **{domain_sim}%**
* **ATS Compatibility Score:** **{ats_score}/100**

---

## 2. Skill Gap Analysis

* **Matched Core Skills:** {matched_str}
* **Missing Target Skills:** {missing_str}

---

## 3. Evidence-Based Strengths
"""
        for s in strengths:
            md += f"- ✓ {s}\n"

        md += "\n## 4. Key Areas for Improvement\n"
        for w in weaknesses:
            md += f"- ⚠ {w}\n"

        md += "\n## 5. Actionable Recommendations\n"
        for imp in recommendations:
            md += f"### {imp.get('category', 'Improvement')}\n"
            md += f"**Guidance:** {imp.get('recommendation', '')}\n\n"

        if res.get("job_match_result", {}).get("success"):
            jm = res["job_match_result"]
            md += f"""---

## 6. Job Description Match

* **Target Job Match Score:** **{jm.get('match_pct', 0)}%**
* **Matched JD Skills:** {', '.join(jm.get('matched_skills', [])) or 'None'}
* **Missing JD Skills:** {', '.join(jm.get('missing_skills', [])) or 'None'}
"""

        md += """\n---
*Disclaimer: ResumeAI scores and suggestions are analytical signals to assist career development and resume optimization.*
"""
        return md

    def generate_pdf_report(self, analysis_result: Dict[str, Any]) -> Path:
        """Renders and saves a PDF report using fpdf2."""
        if not FPDF_AVAILABLE:
            raise RuntimeError("fpdf2 package is required to generate PDF reports.")

        res = analysis_result
        target_domain = res.get("target_domain", "General")
        fit_score = res.get("overall_fit_score", 0)
        rating_label = res.get("rating_label", "Good")
        ats_score = res.get("ats_data", {}).get("ats_score", 0)
        domain_sim = res.get("domain_match_pct", 0)
        personal = res.get("parsed_data", {}).get("personal_info", {})
        cand_name = personal.get("name", "Candidate")

        pdf = PDFReport(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        epw = pdf.epw

        # Metadata box
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(pdf.l_margin, 26, epw, 22, style="FD")

        pdf.set_xy(pdf.l_margin + 5, 28)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(epw / 2 - 5, 8, f"Candidate: {cand_name[:30]}", new_x="RIGHT", new_y="TOP")
        pdf.cell(epw / 2 - 5, 8, f"Target Domain: {target_domain[:30]}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_x(pdf.l_margin + 5)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(epw / 2 - 5, 7, f"Assessment Date: {time.strftime('%b %d, %Y')}", new_x="RIGHT", new_y="TOP")
        pdf.cell(epw / 2 - 5, 7, f"Rating Tier: {rating_label}", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(6)

        # Score Cards Row
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(epw, 7, "Key Performance Indicators", new_x="LMARGIN", new_y="NEXT")

        col_w = epw / 3.0
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(col_w, 8, f"Fit Score: {fit_score}/100", border=1, align="C", new_x="RIGHT", new_y="TOP")
        pdf.cell(col_w, 8, f"Domain Match: {domain_sim}%", border=1, align="C", new_x="RIGHT", new_y="TOP")
        pdf.cell(col_w, 8, f"ATS Score: {ats_score}/100", border=1, align="C", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(5)

        # Skills
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(epw, 7, "Skill Gap Analysis", new_x="LMARGIN", new_y="NEXT")

        matched = res.get("scoring_data", {}).get("skill_alignment", {}).get("matched_skills", [])
        matched_str = ", ".join([s["skill_name"] for s in matched]) if matched else "None detected"

        missing = res.get("scoring_data", {}).get("skill_alignment", {}).get("missing_skills", [])
        missing_str = ", ".join([s["skill_name"] for s in missing[:8]]) if missing else "None"

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(22, 163, 74)
        pdf.cell(epw, 5, "Matched Skills:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(epw, 5, matched_str, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(220, 38, 38)
        pdf.cell(epw, 5, "Missing Target Skills:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(epw, 5, missing_str, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Strengths & Weaknesses
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(epw, 7, "Strengths & Growth Areas", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        for s in res.get("strengths", [])[:3]:
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(epw, 5, f"[+] {s}", new_x="LMARGIN", new_y="NEXT")

        for w in res.get("weaknesses", [])[:3]:
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(epw, 5, f"[!] {w}", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(4)

        # Recommendations
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(epw, 7, "Top Actionable Recommendations", new_x="LMARGIN", new_y="NEXT")

        for imp in res.get("improvements", [])[:3]:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(epw, 5, f"- {imp.get('category')}:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(71, 85, 105)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(epw, 5, imp.get("recommendation", ""), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

        # Save PDF
        report_filename = f"ResumeAI_Report_{int(time.time())}.pdf"
        output_path = REPORTS_DIR / report_filename
        pdf.output(str(output_path))
        return output_path


# Global instance
report_generator = ReportGenerator()
